/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      href: 'https://www.dotnetshare.com'
    }
  },
  {
    name: 'datamanage',
    path: '/datamanage',
    component: 'layout.base',
    meta: {
      title: 'datamanage',
      i18nKey: 'route.datamanage'
    },
    children: [
      {
        name: 'datamanage_user',
        path: '/datamanage/user',
        component: 'view.datamanage_user',
        meta: {
          title: 'datamanage_user',
          i18nKey: 'route.datamanage_user'
        },
        children: [
          {
            name: 'datamanage_user_modules',
            path: '/datamanage/user/modules',
            component: 'view.datamanage_user_modules',
            meta: {
              title: 'datamanage_user_modules',
              i18nKey: 'route.datamanage_user_modules'
            }
          }
        ]
      }
    ]
  },
  {
    name: 'function',
    path: '/function',
    component: 'layout.base',
    meta: {
      title: 'function',
      i18nKey: 'route.function'
    },
    children: [
      {
        name: 'function_hide-child',
        path: '/function/hide-child',
        meta: {
          title: 'function_hide-child',
          i18nKey: 'route.function_hide-child'
        },
        children: [
          {
            name: 'function_hide-child_one',
            path: '/function/hide-child/one',
            component: 'view.function_hide-child_one',
            meta: {
              title: 'function_hide-child_one',
              i18nKey: 'route.function_hide-child_one'
            }
          },
          {
            name: 'function_hide-child_three',
            path: '/function/hide-child/three',
            component: 'view.function_hide-child_three',
            meta: {
              title: 'function_hide-child_three',
              i18nKey: 'route.function_hide-child_three'
            }
          },
          {
            name: 'function_hide-child_two',
            path: '/function/hide-child/two',
            component: 'view.function_hide-child_two',
            meta: {
              title: 'function_hide-child_two',
              i18nKey: 'route.function_hide-child_two'
            }
          }
        ]
      },
      {
        name: 'function_multi-tab',
        path: '/function/multi-tab',
        component: 'view.function_multi-tab',
        meta: {
          title: 'function_multi-tab',
          i18nKey: 'route.function_multi-tab'
        }
      },
      {
        name: 'function_request',
        path: '/function/request',
        component: 'view.function_request',
        meta: {
          title: 'function_request',
          i18nKey: 'route.function_request'
        }
      },
      {
        name: 'function_super-page',
        path: '/function/super-page',
        component: 'view.function_super-page',
        meta: {
          title: 'function_super-page',
          i18nKey: 'route.function_super-page'
        }
      },
      {
        name: 'function_tab',
        path: '/function/tab',
        component: 'view.function_tab',
        meta: {
          title: 'function_tab',
          i18nKey: 'route.function_tab'
        }
      },
      {
        name: 'function_toggle-auth',
        path: '/function/toggle-auth',
        component: 'view.function_toggle-auth',
        meta: {
          title: 'function_toggle-auth',
          i18nKey: 'route.function_toggle-auth'
        }
      }
    ]
  },
  {
    name: 'gallery',
    path: '/gallery',
    component: 'layout.base',
    meta: {
      title: 'gallery',
      i18nKey: 'route.gallery'
    },
    children: [
      {
        name: 'gallery_bing',
        path: '/gallery/bing',
        component: 'view.gallery_bing',
        meta: {
          title: 'gallery_bing',
          i18nKey: 'route.gallery_bing'
        }
      },
      {
        name: 'gallery_category',
        path: '/gallery/category',
        component: 'view.gallery_category',
        meta: {
          title: 'gallery_category',
          i18nKey: 'route.gallery_category'
        }
      },
      {
        name: 'gallery_list',
        path: '/gallery/list',
        component: 'view.gallery_list',
        meta: {
          title: 'gallery_list',
          i18nKey: 'route.gallery_list'
        }
      },
      {
        name: 'gallery_upload',
        path: '/gallery/upload',
        component: 'view.gallery_upload',
        meta: {
          title: 'gallery_upload',
          i18nKey: 'route.gallery_upload'
        }
      },
      {
        name: 'gallery_waterfall',
        path: '/gallery/waterfall',
        component: 'view.gallery_waterfall',
        meta: {
          title: 'gallery_waterfall',
          i18nKey: 'route.gallery_waterfall'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage'
    },
    children: [
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu'
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role'
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user'
        }
      },
      {
        name: 'manage_user-detail',
        path: '/manage/user-detail/:id',
        component: 'view.manage_user-detail',
        meta: {
          title: 'manage_user-detail',
          i18nKey: 'route.manage_user-detail'
        }
      }
    ]
  },
  {
    name: 'multi-menu',
    path: '/multi-menu',
    component: 'layout.base',
    meta: {
      title: 'multi-menu',
      i18nKey: 'route.multi-menu'
    },
    children: [
      {
        name: 'multi-menu_first',
        path: '/multi-menu/first',
        meta: {
          title: 'multi-menu_first',
          i18nKey: 'route.multi-menu_first'
        },
        children: [
          {
            name: 'multi-menu_first_child',
            path: '/multi-menu/first/child',
            component: 'view.multi-menu_first_child',
            meta: {
              title: 'multi-menu_first_child',
              i18nKey: 'route.multi-menu_first_child'
            }
          }
        ]
      },
      {
        name: 'multi-menu_second',
        path: '/multi-menu/second',
        meta: {
          title: 'multi-menu_second',
          i18nKey: 'route.multi-menu_second'
        },
        children: [
          {
            name: 'multi-menu_second_child',
            path: '/multi-menu/second/child',
            meta: {
              title: 'multi-menu_second_child',
              i18nKey: 'route.multi-menu_second_child'
            },
            children: [
              {
                name: 'multi-menu_second_child_home',
                path: '/multi-menu/second/child/home',
                component: 'view.multi-menu_second_child_home',
                meta: {
                  title: 'multi-menu_second_child_home',
                  i18nKey: 'route.multi-menu_second_child_home'
                }
              }
            ]
          }
        ]
      }
    ]
  },
  {
    name: 'plugin',
    path: '/plugin',
    component: 'layout.base',
    meta: {
      title: '插件示例',
      i18nKey: 'route.plugin',
      order: 7,
      icon: 'clarity:plugin-line'
    },
    children: [
      {
        name: 'plugin_barcode',
        path: '/plugin/barcode',
        component: 'view.plugin_barcode',
        meta: {
          title: 'plugin_barcode',
          i18nKey: 'route.plugin_barcode',
          icon: 'ic:round-barcode',
          constant: true
        }
      },
      {
        name: 'plugin_charts',
        path: '/plugin/charts',
        meta: {
          title: 'plugin_charts',
          i18nKey: 'route.plugin_charts',
          icon: 'mdi:chart-areaspline'
        },
        children: [
          {
            name: 'plugin_charts_echarts',
            path: '/plugin/charts/echarts',
            component: 'view.plugin_charts_echarts',
            meta: {
              title: 'plugin_charts_echarts',
              i18nKey: 'route.plugin_charts_echarts',
              icon: 'simple-icons:apacheecharts'
            }
          }
        ]
      },
      {
        name: 'plugin_copy',
        path: '/plugin/copy',
        component: 'view.plugin_copy',
        meta: {
          title: 'plugin_copy',
          i18nKey: 'route.plugin_copy',
          icon: 'mdi:clipboard-outline'
        }
      },
      {
        name: 'plugin_editor',
        path: '/plugin/editor',
        meta: {
          title: 'plugin_editor',
          i18nKey: 'route.plugin_editor',
          icon: 'icon-park-outline:editor'
        },
        children: [
          {
            name: 'plugin_editor_markdown',
            path: '/plugin/editor/markdown',
            component: 'view.plugin_editor_markdown',
            meta: {
              title: 'plugin_editor_markdown',
              i18nKey: 'route.plugin_editor_markdown',
              icon: 'ri:markdown-line'
            }
          },
          {
            name: 'plugin_editor_quill',
            path: '/plugin/editor/quill',
            component: 'view.plugin_editor_quill',
            meta: {
              title: 'plugin_editor_quill',
              i18nKey: 'route.plugin_editor_quill',
              icon: 'mdi:file-document-edit-outline'
            }
          }
        ]
      },
      {
        name: 'plugin_excel',
        path: '/plugin/excel',
        component: 'view.plugin_excel',
        meta: {
          title: 'plugin_excel',
          i18nKey: 'route.plugin_excel'
        }
      },
      {
        name: 'plugin_icon',
        path: '/plugin/icon',
        component: 'view.plugin_icon',
        meta: {
          title: 'plugin_icon',
          i18nKey: 'route.plugin_icon',
          localIcon: 'simple-icons:swiper'
        }
      },
      {
        name: 'plugin_map',
        path: '/plugin/map',
        component: 'view.plugin_map',
        meta: {
          title: 'plugin_map',
          i18nKey: 'route.plugin_map',
          icon: 'mdi:map'
        }
      },
      {
        name: 'plugin_pdf',
        path: '/plugin/pdf',
        component: 'view.plugin_pdf',
        meta: {
          title: 'plugin_pdf',
          i18nKey: 'route.plugin_pdf'
        }
      },
      {
        name: 'plugin_print',
        path: '/plugin/print',
        component: 'view.plugin_print',
        meta: {
          title: 'plugin_print',
          i18nKey: 'route.plugin_print',
          icon: 'mdi:printer'
        }
      },
      {
        name: 'plugin_swiper',
        path: '/plugin/swiper',
        component: 'view.plugin_swiper',
        meta: {
          title: 'plugin_swiper',
          i18nKey: 'route.plugin_swiper',
          icon: 'simple-icons:swiper'
        }
      },
      {
        name: 'plugin_typeit',
        path: '/plugin/typeit',
        component: 'view.plugin_typeit',
        meta: {
          title: 'plugin_typeit',
          i18nKey: 'route.plugin_typeit'
        }
      },
      {
        name: 'plugin_video',
        path: '/plugin/video',
        component: 'view.plugin_video',
        meta: {
          title: 'plugin_video',
          i18nKey: 'route.plugin_video',
          icon: 'mdi:video'
        }
      }
    ]
  },
  {
    name: 'syslog',
    path: '/syslog',
    component: 'layout.base',
    meta: {
      title: 'syslog',
      i18nKey: 'route.syslog'
    },
    children: [
      {
        name: 'syslog_logerr',
        path: '/syslog/logerr',
        component: 'view.syslog_logerr',
        meta: {
          title: 'syslog_logerr',
          i18nKey: 'route.syslog_logerr'
        }
      },
      {
        name: 'syslog_logop',
        path: '/syslog/logop',
        component: 'view.syslog_logop',
        meta: {
          title: 'syslog_logop',
          i18nKey: 'route.syslog_logop'
        }
      },
      {
        name: 'syslog_logvis',
        path: '/syslog/logvis',
        component: 'view.syslog_logvis',
        meta: {
          title: 'syslog_logvis',
          i18nKey: 'route.syslog_logvis'
        }
      }
    ]
  },
  {
    name: 'sysmanage',
    path: '/sysmanage',
    component: 'layout.base',
    meta: {
      title: 'sysmanage',
      i18nKey: 'route.sysmanage'
    },
    children: [
      {
        name: 'sysmanage_cache',
        path: '/sysmanage/cache',
        component: 'view.sysmanage_cache',
        meta: {
          title: 'sysmanage_cache',
          i18nKey: 'route.sysmanage_cache'
        }
      },
      {
        name: 'sysmanage_config',
        path: '/sysmanage/config',
        component: 'view.sysmanage_config',
        meta: {
          title: 'sysmanage_config',
          i18nKey: 'route.sysmanage_config'
        }
      },
      {
        name: 'sysmanage_dic',
        path: '/sysmanage/dic',
        component: 'view.sysmanage_dic',
        meta: {
          title: 'sysmanage_dic',
          i18nKey: 'route.sysmanage_dic'
        }
      },
      {
        name: 'sysmanage_online-user',
        path: '/sysmanage/online-user',
        component: 'view.sysmanage_online-user',
        meta: {
          title: 'sysmanage_online-user',
          i18nKey: 'route.sysmanage_online-user'
        }
      },
      {
        name: 'sysmanage_systemstatus',
        path: '/sysmanage/systemstatus',
        component: 'view.sysmanage_systemstatus',
        meta: {
          title: 'sysmanage_systemstatus',
          i18nKey: 'route.sysmanage_systemstatus'
        }
      },
      {
        name: 'sysmanage_usercenter',
        path: '/sysmanage/usercenter',
        component: 'view.sysmanage_usercenter',
        meta: {
          title: 'sysmanage_usercenter',
          i18nKey: 'route.sysmanage_usercenter'
        }
      }
    ]
  }
];
